rootProject.name = "ldocs"
include(":platform:common-meta")
include(":platform:gradle-plugin")
include(":platform:common-core")
include(":platform:server-core")
include(":platform:server-atomikos")
include(":platform:server-file-storage")
include(":platform:server-postgres")
include(":platform:server-mongo")
include(":server:modules:ldocs-core")
include(":server:modules:ldocs-rgd")
include(":server:modules:sete")
include(":server:modules:xdisk")
include(":server:projects:sete")
include(":server:projects:xdisk")
includeBuild("frontend-rgd")
includeBuild("frontend-xdisk")
includeBuild("agent")
