include("gradle-plugins:internal")
include("gradle-plugins:elsa")
include("platform:meta")
include("platform:common")
include("platform:server")
include("platform:server-postgres")
include("platform:server-tomcat")
include("platform:server-atomikos")
include("platform:server-file-storage")
include("platform:server-jms")
include("platform:sjl")
include("platform:web-common")
include("demo:server")
rootProject.name ="elsa"
