name: demo-server
services:

  db:
    image: postgres:15.3
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d demo" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
