{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine",
    "module": "elsa-meta",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "elsa-meta-0.0.1.jar",
          "url": "elsa-meta-0.0.1.jar",
          "size": 32302,
          "sha512": "02b777c61e7aebbd5e3ef5cb6a94ac414d7befe1ea3a4ffc6f7005711ba4dd10dfa56a79063dd117db4b2e6f7e2aeef890de338424941cb0fdc1c6ea6551ac3a",
          "sha256": "733b257511ed89c8f54cee5031ec56ae21f463b46cf9763caa5cbfcab1330fac",
          "sha1": "a5d0024fa80d013e5b2605f45dd63851dd96474c",
          "md5": "bf9909a7cef31182a0f38ce47c1868df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2+"
          }
        }
      ],
      "files": [
        {
          "name": "elsa-meta-0.0.1.jar",
          "url": "elsa-meta-0.0.1.jar",
          "size": 32302,
          "sha512": "02b777c61e7aebbd5e3ef5cb6a94ac414d7befe1ea3a4ffc6f7005711ba4dd10dfa56a79063dd117db4b2e6f7e2aeef890de338424941cb0fdc1c6ea6551ac3a",
          "sha256": "733b257511ed89c8f54cee5031ec56ae21f463b46cf9763caa5cbfcab1330fac",
          "sha1": "a5d0024fa80d013e5b2605f45dd63851dd96474c",
          "md5": "bf9909a7cef31182a0f38ce47c1868df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elsa-meta-0.0.1-sources.jar",
          "url": "elsa-meta-0.0.1-sources.jar",
          "size": 22045,
          "sha512": "5f156c9e81a69c55d7afeb645c897232269e2cdb39a816c600661e5c8480a5eb9d4c5c87e28711d7fd43dc898b7303f54c0519f8d0c631a53de65fa38371b7a6",
          "sha256": "69c02f7a8957768feae6b1629d5615e2f54e6e3ccb5cdea94c0bcb05211ff01c",
          "sha1": "0b2447b8529847dc9c94e2dcc46c257541e8ac7a",
          "md5": "3a0312eedd0258f51f69a845331deac9"
        }
      ]
    }
  ]
}
