{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine",
    "module": "elsa-gradle",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "elsa-gradle-0.0.1.jar",
          "url": "elsa-gradle-0.0.1.jar",
          "size": 161938,
          "sha512": "7f70fbc84f0389df3c25163232f284265285a55d7dcf19dcd76862739cb5e611fdca08470ce95c1c9c92cf3afe9e88e6c4e6f023725b7e6973dba870d931a370",
          "sha256": "0648942932a1b23401f8e8115576141c2f41529ea4f8eeec1272310c874a71d2",
          "sha1": "6d2b3ad8952ef2bdf5495484b5626d7d984e4ab0",
          "md5": "8a9831bd0b1d798a54bd788449ed3a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gridnine",
          "module": "elsa-meta",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "elsa-gradle-0.0.1.jar",
          "url": "elsa-gradle-0.0.1.jar",
          "size": 161938,
          "sha512": "7f70fbc84f0389df3c25163232f284265285a55d7dcf19dcd76862739cb5e611fdca08470ce95c1c9c92cf3afe9e88e6c4e6f023725b7e6973dba870d931a370",
          "sha256": "0648942932a1b23401f8e8115576141c2f41529ea4f8eeec1272310c874a71d2",
          "sha1": "6d2b3ad8952ef2bdf5495484b5626d7d984e4ab0",
          "md5": "8a9831bd0b1d798a54bd788449ed3a38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "elsa-gradle-0.0.1-sources.jar",
          "url": "elsa-gradle-0.0.1-sources.jar",
          "size": 67494,
          "sha512": "673661749e127799183781e017c6b4ebafe53efcdff6e8cb97a192f1ec4340baec963834e7e711e3ccc63f76b7411f7a766b79e71b83a2a5693f6d12a3ff461d",
          "sha256": "33f7918ac802f0a53aa4bb901dfae60e3e6b9dc8bb5beb66a612dc6a8e963879",
          "sha1": "0507f2e1246f5082fac31159d60c2fccf05368b4",
          "md5": "bfdedf3ddcbe650576fc5a88023eb9e0"
        },
        {
          "name": "elsa-gradle-0.0.1-sources.jar",
          "url": "elsa-gradle-0.0.1-sources.jar",
          "size": 67494,
          "sha512": "673661749e127799183781e017c6b4ebafe53efcdff6e8cb97a192f1ec4340baec963834e7e711e3ccc63f76b7411f7a766b79e71b83a2a5693f6d12a3ff461d",
          "sha256": "33f7918ac802f0a53aa4bb901dfae60e3e6b9dc8bb5beb66a612dc6a8e963879",
          "sha1": "0507f2e1246f5082fac31159d60c2fccf05368b4",
          "md5": "bfdedf3ddcbe650576fc5a88023eb9e0"
        }
      ]
    }
  ]
}
