version: 1

server:
  port: 8080
  externalAddress: https://rgd.gridnine.com

elsa:
  storage:
    type: STANDARD
    databaseType: SIMPLE-ATOMIKOS
    adapter: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:xdisk}?loginTimeout=10
    poolSize: 20
    login: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}

logging:
  level:
    root: INFO
    com.gridnine: DEBUG
    com.atomikos.datasource.xa.XATransactionalResource: ERROR

keycloak:
  localDevelopmentUserName: ${KEYCLOAK_DEVELOPMENT_USER_NAME:#{null}}
  clientId: ${KEYCLOAK_CLIENT_ID:xdisk-server}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:OadBv345iC9lWYPaEMCXlP1VixM9GRVU}
  externalUrl: ${KEYCLOAK_EXTERNAL_URL:http://localhost:8888}
  realm: ${KEYCLOAK_REALM:xdisk}
  redirectUrl: ${KEYCLOAK_REDIRECT_URL:http://localhost:8080/internal/keycloak-redirect}
  adminUsername: admin
  adminPassword: admin
  tasksCronExpression: ${KEYCLOAK_TASKS_CRON:#{null}}


xdisk:
  parsers:
    clientsAndMatters:
      folder: import/clientsAndMatters
      cron: 0 * * * * *
  sample-data.generate: true