{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gridnine",
    "module": "elsa-gradle-internal",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "elsa-gradle-internal-0.0.1.jar",
          "url": "elsa-gradle-internal-0.0.1.jar",
          "size": 11636,
          "sha512": "a7816cc94e02763051b4310d75ea095744e515f3e125462c9235966c2b2c2d493d07eb3bc5ed073a81d557ad11c5beb983c8e9feeec6fa1221ec875bdffb098b",
          "sha256": "355d1111161e3c06e3fd7fe84376b9ed103ab3ca0feff9ac0fb13ff1e1e79c82",
          "sha1": "544854ca007c3f29f691346c32c2da63c7497a73",
          "md5": "a8b4f382634b16e8a5f84027b8796b1c"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "elsa-gradle-internal-0.0.1.jar",
          "url": "elsa-gradle-internal-0.0.1.jar",
          "size": 11636,
          "sha512": "a7816cc94e02763051b4310d75ea095744e515f3e125462c9235966c2b2c2d493d07eb3bc5ed073a81d557ad11c5beb983c8e9feeec6fa1221ec875bdffb098b",
          "sha256": "355d1111161e3c06e3fd7fe84376b9ed103ab3ca0feff9ac0fb13ff1e1e79c82",
          "sha1": "544854ca007c3f29f691346c32c2da63c7497a73",
          "md5": "a8b4f382634b16e8a5f84027b8796b1c"
        }
      ]
    }
  ]
}
